module-name: kyma-companion
kind: kcp
bdba:
  # kyma-companion
  - europe-docker.pkg.dev/kyma-project/prod/kyma-companion:0.5.0
  # doc-indexer
  - europe-docker.pkg.dev/kyma-project/prod/kyma-companion-indexer:0.5.0
checkmarx-one:
  preset: python-default
  exclude:
    - "tests/**"
    - "**/tests/**"
mend:
  language: python
  exclude:
    - "tests/**"
    - "**/tests/**"
